# Site settings
baseurl: "/demojekyll"
name: demo jekyll
theme: "classic"

# Build settings
markdown: kramdown
# permalink: ordinal
permalink: /:categories/:title-090xx.html
excerpt_separator: "\n\n"
paginate: 12