# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/demojekyll" # the subpath of your site, e.g. /blog/
url: "http://vitinhkk.github.io" # the base hostname & protocol for your site
name: demo jekyll
theme: "classic"

# Build settings
markdown: kramdown
permalink: /:title:output_ext
excerpt_separator: "\n\n"
paginate: 12